"""
This type stub file was generated by pyright.
"""

import pandas as pd
from importlib import resources
from pandas.api.types import is_object_dtype

""" Sample prices data """
TIMEZONE = ...
FREQUENCIES = ...
def sample_prices(freq: str = ..., *, max_bars: int = ..., item: str = ...): # -> Series | DataFrame:
    """Sample prices"""
    ...

