from typing import Any
import numpy as np

def calc_abs(series) -> np.ndarray: ...
def calc_adx(prices, period=14) -> np.ndarray: ...
def calc_alma(series, period=9, offset=0.85, sigma=6.0) -> np.ndarray: ...
def calc_atr(prices, period=14) -> np.ndarray: ...
def calc_avgprice(prices) -> np.ndarray: ...
def calc_bbands(prices, period=20, nbdev=2.0) -> Any: ...
def calc_bbp(prices, period=20, nbdev=2.0) -> np.ndarray: ...
def calc_bbw(prices, period=20, nbdev=2.0) -> np.ndarray: ...
def calc_bop(prices, period=20) -> np.ndarray: ...
def calc_cci(prices, period=20) -> np.ndarray: ...
def calc_clag(series, period=1) -> np.ndarray: ...
def calc_cmf(prices, period=20) -> np.ndarray: ...
def calc_crossover(series, level=0.0) -> np.ndarray: ...
def calc_crossunder(series, level=0.0) -> np.ndarray: ...
def calc_curve(series, period=20) -> np.ndarray: ...
def calc_dema(series, period) -> np.ndarray: ...
def calc_diff(series, period=1) -> np.ndarray: ...
def calc_dmi(prices, period=14) -> Any: ...
def calc_donchian(prices, period=20) -> Any: ...
def calc_ema(series, period, *, adjust=False) -> np.ndarray: ...
def calc_eval(prices, expr, *, as_flag=False) -> np.ndarray: ...
def calc_exp(series) -> np.ndarray: ...
def calc_flag(series) -> np.ndarray: ...
def calc_hma(series, period) -> np.ndarray: ...
def calc_kama(series, period=10, fastn=2, slown=30) -> np.ndarray: ...
def calc_keltner(prices, period=20, nbatr=2.0) -> Any: ...
def calc_ker(series, period=10) -> np.ndarray: ...
def calc_lag(series, period) -> np.ndarray: ...
def calc_log(series) -> np.ndarray: ...
def calc_lroc(series, period=1) -> np.ndarray: ...
def calc_macd(series, n1=12, n2=26, n3=9) -> Any: ...
def calc_macdv(prices, n1=12, n2=26, n3=9) -> Any: ...
def calc_mad(series, period=14) -> np.ndarray: ...
def calc_mav(series, period=20, *, ma_type='SMA') -> np.ndarray: ...
def calc_max(series, period) -> np.ndarray: ...
def calc_mdi(prices, period=14) -> np.ndarray: ...
def calc_mfi(prices, period=14) -> np.ndarray: ...
def calc_midprice(prices) -> np.ndarray: ...
def calc_min(series, period) -> np.ndarray: ...
def calc_natr(prices, period=14) -> np.ndarray: ...
def calc_pdi(prices, period=14) -> np.ndarray: ...
def calc_ppo(series, n1=12, n2=26, n3=9) -> Any: ...
def calc_price(prices, item: str | None = None) -> np.ndarray: ...
def calc_qsf(series, period=20, offset=0) -> np.ndarray: ...
def calc_rma(series, period) -> np.ndarray: ...
def calc_roc(series, period=1) -> np.ndarray: ...
def calc_rsi(series, period=14) -> np.ndarray: ...
def calc_rvalue(series, period=20) -> np.ndarray: ...
def calc_sar(prices, afs=0.02, maxaf=0.2) -> np.ndarray: ...
def calc_sign(series) -> np.ndarray: ...
def calc_slope(series, period=20) -> np.ndarray: ...
def calc_sma(series, period) -> np.ndarray: ...
def calc_stdev(series, period=20) -> np.ndarray: ...
def calc_step(series, threshold: float = 1.0) -> np.ndarray: ...
def calc_stoch(prices, period=14, fastn=3, slown=3) -> Any: ...
def calc_streak(series) -> np.ndarray: ...
def calc_sum(series, period) -> np.ndarray: ...
def calc_tema(series, period=20) -> np.ndarray: ...
def calc_trange(prices, *, log_prices=False, percent=False) -> np.ndarray: ...
def calc_tsf(series, period=20, offset=0) -> np.ndarray: ...
def calc_typprice(prices) -> np.ndarray: ...
def calc_updown(series, up_level=0.0, down_level=0.0) -> np.ndarray: ...
def calc_wclprice(prices) -> np.ndarray: ...
def calc_wma(series, period) -> np.ndarray: ...
def column_accessor(data) -> Any: ...
def get_series(data, item: str | None = None, *, default_item: str = 'close') -> Any: ...
def wrap_result(result, source, name: str | None = None) -> Any: ...
