import numpy as np

def calc_abs(series) -> np.ndarray: ...
def calc_adx(high, low, close, period=14) -> np.ndarray: ...
def calc_alma(series, period=9, offset=0.85, sigma=6.0) -> np.ndarray: ...
def calc_atr(high, low, close, period=14) -> np.ndarray: ...
def calc_avgprice(open, high, low, close) -> np.ndarray: ...
def calc_bbands(series, period=20, nbdev=2.0) -> tuple: ...
def calc_bbp(series, period=20, nbdev=2.0) -> np.ndarray: ...
def calc_bbw(series, period=20, nbdev=2.0) -> np.ndarray: ...
def calc_bop(open, high, low, close) -> np.ndarray: ...
def calc_cci(high, low, close, period=20) -> np.ndarray: ...
def calc_clag(series, period=1) -> np.ndarray: ...
def calc_cmf(high, low, close, volume, period=20) -> np.ndarray: ...
def calc_crossover(series, level=0.0) -> np.ndarray: ...
def calc_crossunder(series, level=0.0) -> np.ndarray: ...
def calc_dema(series, period) -> np.ndarray: ...
def calc_diff(series, period=1) -> np.ndarray: ...
def calc_dmi(high, low, close, period=14) -> tuple: ...
def calc_donchian(high, low, period=20) -> tuple: ...
def calc_ema(series, period, *, adjust=False) -> np.ndarray: ...
def calc_exp(series) -> np.ndarray: ...
def calc_flag(series) -> np.ndarray: ...
def calc_hma(series, period) -> np.ndarray: ...
def calc_kama(series, period=10, fastn=2, slown=30) -> np.ndarray: ...
def calc_keltner(high, low, close, period=20, nbatr=2.0) -> tuple: ...
def calc_ker(series, period=10) -> np.ndarray: ...
def calc_lag(series, period) -> np.ndarray: ...
def calc_linreg(series, period=20, offset=0) -> np.ndarray: ...
def calc_linreg_rmse(series, period=20) -> np.ndarray: ...
def calc_linreg_rvalue(series, period=20) -> np.ndarray: ...
def calc_linreg_slope(series, period=20) -> np.ndarray: ...
def calc_log(series) -> np.ndarray: ...
def calc_lroc(series, period=1) -> np.ndarray: ...
def calc_macd(series, n1=12, n2=26, n3=9) -> tuple: ...
def calc_macdv(high, low, close, n1=12, n2=26, n3=9) -> tuple: ...
def calc_mad(series, period=14) -> np.ndarray: ...
def calc_mav(series, period=20, *, matype='sma') -> np.ndarray: ...
def calc_max(series, period) -> np.ndarray: ...
def calc_mdi(high, low, close, period=14) -> np.ndarray: ...
def calc_medprice(high, low) -> np.ndarray: ...
def calc_mfi(high, low, close, volume, period=14) -> np.ndarray: ...
def calc_min(series, period) -> np.ndarray: ...
def calc_natr(high, low, close, period=14) -> np.ndarray: ...
def calc_obv(close, volume) -> np.ndarray: ...
def calc_pdi(high, low, close, period=14) -> np.ndarray: ...
def calc_ppo(series, n1=12, n2=26, n3=9) -> tuple: ...
def calc_quadreg(series, period=20, offset=0) -> np.ndarray: ...
def calc_quadreg_curve(series, period=20) -> np.ndarray: ...
def calc_quadreg_rmse(series, period=20) -> np.ndarray: ...
def calc_quadreg_rvalue(series, period=20) -> np.ndarray: ...
def calc_quadreg_slope(series, period=20, offset=0) -> np.ndarray: ...
def calc_rma(series, period) -> np.ndarray: ...
def calc_roc(series, period=1) -> np.ndarray: ...
def calc_rocp(series, period=1) -> np.ndarray: ...
def calc_rsi(series, period=14) -> np.ndarray: ...
def calc_sar(high, low, afs=0.02, maxaf=0.2) -> np.ndarray: ...
def calc_sign(series) -> np.ndarray: ...
def calc_sma(series, period) -> np.ndarray: ...
def calc_stdev(series, period=20) -> np.ndarray: ...
def calc_step(series, threshold: float = 1.0) -> np.ndarray: ...
def calc_stoch(high, low, close, period=14, fastn=3, slown=3) -> tuple: ...
def calc_streak(series) -> np.ndarray: ...
def calc_sum(series, period) -> np.ndarray: ...
def calc_tema(series, period=20) -> np.ndarray: ...
def calc_trange(high, low, close) -> np.ndarray: ...
def calc_typprice(high, low, close) -> np.ndarray: ...
def calc_updown(series, up_level=0.0, down_level=0.0) -> np.ndarray: ...
def calc_wclprice(high, low, close) -> np.ndarray: ...
def calc_wma(series, period) -> np.ndarray: ...
def calc_zlema(series, period) -> np.ndarray: ...
