"""
Polars Expression Factory Methods
"""

# Do not edit! This file was generated.

import polars as pl

from typing import TypeAlias

from mintalib import core
from mintalib.model.expression import wrap_expression

IntoExpr: TypeAlias = pl.Expr | str | None

CLOSE = pl.col('close')
OHLC = pl.struct(['open', 'high', 'low', 'close'])

@wrap_expression(core.calc_abs)
def abs(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_adx)
def adx(period: int = 14, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_alma)
def alma(period: int = 9, offset: float = 0.85, sigma: float = 6.0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_atr)
def atr(period: int = 14, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_avgprice)
def avgprice(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_bbands)
def bbands(period: int = 20, nbdev: float = 2.0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_bbp)
def bbp(period: int = 20, nbdev: float = 2.0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_bbw)
def bbw(period: int = 20, nbdev: float = 2.0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_bop)
def bop(period: int = 20, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_cci)
def cci(period: int = 20, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_clag)
def clag(period: int = 1, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_cmf)
def cmf(period: int = 20, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_crossover)
def crossover(level: float = 0.0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_crossunder)
def crossunder(level: float = 0.0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_curve)
def curve(period: int = 20, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_dema)
def dema(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_diff)
def diff(period: int = 1, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_dmi)
def dmi(period: int = 14, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_ema)
def ema(period: int, *, adjust: bool = False, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_exp)
def exp(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_flag)
def flag(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_hma)
def hma(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_kama)
def kama(period: int = 10, fastn: int = 2, slown: int = 30, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_keltner)
def keltner(period: int = 20, nbatr: float = 2.0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_ker)
def ker(period: int = 10, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_lag)
def lag(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_log)
def log(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_lroc)
def lroc(period: int = 1, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_macd)
def macd(n1: int = 12, n2: int = 26, n3: int = 9, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_macdv)
def macdv(n1: int = 12, n2: int = 26, n3: int = 9, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_mad)
def mad(period: int = 14, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_mav)
def mav(period: int = 20, *, ma_type: str = 'SMA', src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_max)
def max(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_mdi)
def mdi(period: int = 14, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_mfi)
def mfi(period: int = 14, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_midprice)
def midprice(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_min)
def min(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_natr)
def natr(period: int = 14, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_pdi)
def pdi(period: int = 14, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_ppo)
def ppo(n1: int = 12, n2: int = 26, n3: int = 9, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_price)
def price(item: str = None, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_qsf)
def qsf(period: int = 20, offset: int = 0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_rma)
def rma(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_roc)
def roc(period: int = 1, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_rsi)
def rsi(period: int = 14, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_rvalue)
def rvalue(period: int = 20, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_sar)
def sar(afs: float = 0.02, maxaf: float = 0.2, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_shift)
def shift(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_sign)
def sign(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_slope)
def slope(period: int = 20, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_sma)
def sma(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_stdev)
def stdev(period: int = 20, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_step)
def step(threshold: 'float' = 1.0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_stoch)
def stoch(period: int = 14, fastn: int = 3, slown: int = 3, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_streak)
def streak(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_sum)
def sum(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_tema)
def tema(period: int = 20, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_trange)
def trange(*, log_prices: bool = False, percent: bool = False, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_tsf)
def tsf(period: int = 20, offset: int = 0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_typprice)
def typprice(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_updown)
def updown(up_level: float = 0.0, down_level: float = 0.0, *, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_wclprice)
def wclprice(*, src: IntoExpr = None) -> pl.Expr: ...

@wrap_expression(core.calc_wma)
def wma(period: int, *, src: IntoExpr = None) -> pl.Expr: ...

