"""
This type stub file was generated by pyright.
"""

from typing import Callable
from inspect import Parameter

""" helper utilities """
def first_param(func: Callable): # -> str | None:
    """Name of function's first parameter if any"""
    ...

def sample_param(param: Parameter): # -> Literal['close', 20]:
    """Sample value for parameters without ac default value"""
    ...

def sample_params(func: Callable) -> dict:
    """Dictionary of sample parameter values"""
    ...

