"""
This type stub file was generated by pyright.
"""

"""Mintalib Utils"""
def format_partial(func, data, *, name: str = ...): # -> str:
    """format a partial function call"""
    ...

def lazy_repr(obj): # -> str:
    """minimal __repr__ based on __init__ signature"""
    ...

